### ISSUE TITLE
Code sample doesn't work

### ISSUE THREAD

**Issue by kharandziuk** [Reactive-Extensions/rx-node#10]
I run the sample below and see nothing in console

```
var Rx = require('rx');
var RxNode = require('rx-node');

var source = Rx.Observable.range(0, 5);

var subscription = RxNode.writeToStream(source, process.stdout, 'utf8');
```

```
├── rx@2.5.3
├─┬ rx-node@1.0.0
│ └── rx@2.5.3
```

Did I miss something?

**Comment by paulpdaniels** [comment]
You aren't missing anything, this issue was fixed in PR #8.
The npm package is just out of date.

@mattpodwysocki could you update the package to the latest version so we can get this fix?

**Comment by paulpdaniels** [comment]
Just saw this issue again on [stackoverflow](http://stackoverflow.com/questions/30834085/rx-node-writetostream-not-emitting-output-to-process-stdout/30857250#30857250)

**Comment by mattpodwysocki** [comment]
@paulpdaniels done
