### ISSUE TITLE
`fromEvent` does not exist

### ISSUE THREAD

**Issue by sergi** [Reactive-Extensions/rx-node#5]
The [docs](https://github.com/Reactive-Extensions/rx-node/blob/master/doc/api/nodejs.md#rxnodefromeventeventemitter-eventname) have a `fromEvent` method, but `rx-node` doesn't include it. In any case, should it be `fromEventEmitter`, given that there is `toEventEmitter`?

**Comment by jaawerth** [comment]
I recently noticed this as well. It appears that core Rx's `fromEvent`  [now supports node EventEmitters out of the box](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/events.md#converting-a-nodejs-event-to-a-rxjs-observable-sequence) (I just gave it a try to be sure), so this appears to be a case where the solution is to update that part of the rx-node docs with a note saying as much.

**Comment by ariutta** [comment]
I should have referenced this issue from my pull request that addresses it: https://github.com/Reactive-Extensions/rx-node/pull/9

**Comment by mattpodwysocki** [comment]
@sergi done
